### PR TITLE
Larger sign up button

### PR DESCRIPTION
**Pull request by walaura**
screen shot 2018-03-26 at 3 46 02 pm

Not a fan of the visual design but it is larger and more prominent

@katyabeer

### CODE REVIEW

**Comment by katyabeer** [comment]
It's hoooooooge! :)

**Comment by katyabeer** [comment]
A couple of things: 
- Copy: "New to the Guardian?"
- Button copy: 'Create an account'.
- Can we shorten the button somehow? :) At the moment it's quite a sausage!

**Comment by jfsoul** [comment]
Putting my paranoid hat on - the new copy `New to The Guardian?` might not be applicable in all cases.  People can be very familiar with the Guardian - even have a paying relationship without having an account.

Also @katyabeer what was wrong with `Sign up`? `Create an account` sounds so formal.

**Comment by katyabeer** [comment]
@jfsoul 

"New to the Guardian?" - Good point. Will double-check the wording with Celine asap.

'Create an account':

- It's not good practice to have ‘Sign In’ and ‘Sign Up’ on the same page/as a combination. When buttons/CTAs both use the same verb in their labels it’s easy for users to get confused. Even if users didn’t make the mistake of clicking on the wrong button, they’ll spend extra time distinguishing the two. So we either use Sign in / Register. Or Sign in / Create an account. Since the Sign up page is actually called 'Create your Guardian account' I'd keep it consistent... https://profile.theguardian.com/register?returnUrl=https%3A%2F%2Fwww.theguardian.com%2Fuk

**Comment by katyabeer** [comment]
I've just spoken to Celine. She's fine with 'New to the Guardian?' because of the context that line appears in. It is implied that on the 'Sign page' the context is about having an account and **being** a **new** (or returning) user.

**Pull request merged**
