### PR TITLE
Use sbt v0.13.13 for faster compile times!

### PR DESCRIPTION
**Pull request by rtyley**
cc @svillafe

### CODE REVIEW

**Comment by TBonnin** [comment]
@rtyley I am curious: How much faster is it? Upgrading to sbt 0.13.13 on frontend didn't bring any improvement, at least on a clean compile

**Comment by rtyley** [comment]
Using SBT v0.13.13 for compilation speedup was a recommendation by Rory Graves at Scala eXchange 2016 in his talk [_"Can ScalaC be 10 times faster?"_](https://skillsmatter.com/skillscasts/9042-can-scalac-be-10-times-faster) - it's in the video at 9m35s.

The speed-up comes from SBT PR https://github.com/sbt/sbt/pull/2754 (_"Recycle classloaders to be anti-hostile to JIT"_) - Rory measured a 20% speed up on his project using SBT v0.13.13 over v0.13.12. On this project, looking 4 Circle CI builds (2 identical builds of this branch, 2 identical builds of master), I see a **~10%** reduction in compilation time.

## Circle CI timings

On master, which uses SBT 0.13.9 - **4m13s, 4m11s** for `sbt test:compile`:
image
image


On this branch, using SBT 0.13.13 - **3m52s, 3m45s** for `sbt test:compile`:
image
image

**Comment by TBonnin** [comment]
Thanks. That's a pretty good result.

**Comment by retronym** [comment]
> On this project, looking 4 Circle CI builds (2 identical builds of this branch, 2 identical builds of master), I see a ~10% reduction in compilation time.

Glad to see you've got some benefits after upgrading. I just wanted to note that the benefits are more pronounced when using a long-running SBT process to do compilation, ie leaving an SBT shell open in a terminal and repeatedly running `compile`. My [benchmarks suggest](https://github.com/scala/compiler-benchmark/pull/30#issuecomment-309596835) a 25% improvement for that scenario.

**Pull request merged**
